services:

    servidor-web:
        container_name:     miapache
        image:              httpd:latest
        ports:
            - 8082:80
        volumes:
            - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
            - /home/ubuntu/environment/datos/apache/logs:/usr/local/apache2/logs
    
    filebeat:
        container_name:     mifilebeat
        image:              docker.elastic.co/beats/filebeat:8.16.1
        volumes:            
            - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
            - /home/ubuntu/environment/datos/apache/logs:/tmp/logs

    
    logstash: # fqdn que se da alta en el dns interno de docker 
              # Y nos permite desde otro contenedor referenciar a este
        container_name:     milogstash
        image:              docker.elastic.co/logstash/logstash:8.16.1
        volumes:            
            - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
            - /home/ubuntu/environment/datos/elastic/certs/ca/ca.crt:/usr/share/logstash/certs/ca/ca.crt
