filebeat.inputs:
- type: log
  paths:
    - /tmp/logs/access_log


output.logstash:
  hosts: ["logstash:5044"] # fqdn con el que dreferirnos al servidor (contenedor) que corre logstash
  
#output.console:
  #pretty: true
